spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/orders_db
    username: postgres
    password: postgres
  redis:
    host: redis
    port: 6379
  kafka:
    bootstrap-servers: kafka:9092