apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: chimebuka/order-service:v1
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://host.docker.internal:5435/orders_db

            - name: SPRING_DATASOURCE_USERNAME
              value: postgres

            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres

            - name: SPRING_REDIS_HOST
              value: host.docker.internal

            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: host.docker.internal:9092